### ISSUE TITLE
Help button

### ISSUE THREAD

**Issue by Duragtan** [DFscript/Covid_19_data_visualisation#12]
The already drafted help text, giving information on the usage and the context of the site, still needs to be included into the page.

**Comment by Duragtan** [comment]
Help text to be found in frontend-directory.

I also drafted a help icon to be found in the same directory.

**Comment by gooney47** [comment]
https://github.com/DFscript/Covid_19_data_visualisation/commit/d032f629b55496fa77fa4270fda18b28de1b5630
Solved this issue.
