### ISSUE TITLE
A little space between the switches at the bottom

### ISSUE THREAD

**Issue by Duragtan** [DFscript/Covid_19_data_visualisation#13]
The labels of the switches at the bottom of the bar chart touch one another. There should be some space between them (at least 1.5m ;-P)

**Comment by Duragtan** [comment]
![Screenshot_2020-03-22 Dash(6)](https://user-images.githubusercontent.com/35807717/77259510-3b9e4d80-6c82-11ea-95ed-dbb19da3edf6.png)

**Comment by gooney47** [comment]
They got integrated into the checklist.
